ferbihu/PF-GRUPAL

client/src/App.js, client/src/Components/Footer/Footer.jsx
=> Estructura Footer

client/package-lock.json, client/package.json, client/src/Components/Mapa/Map.jsx, client/src/Pages/LugaresSeguros.jsx, package-lock.json
mapa funcional con puntos aleatorios
=> mapfuncional

api2/index.js, api2/src/controllers/safeplace.js, api2/src/db.js, api2/src/models/safePlace.js, api2/src/routes/safeplace.js, api2/src/services/safeplace.js, client/package-lock.json
chicas les dejo el post y el get de los lugares seguros, agregue algunas cosas a la base de dato para que me cree bien la relacion, cambie el force a false, asi no se me borraban a cada rato los datos que iba poniendo en la tabla , y en los modelos cambie de INTEGER A DOUBLE la latitud y la longitud
=> Post-get -Safe-Place

client/src/Pages/Registro-Usuario/Registrate.css, client/src/Pages/Registro-Usuario/Registrate.jsx, client/src/actions/actions.js
[x] Formulario registro-usuario. 
[x] Faltan funcionalidades.
=> Formulario registro-usuario

api2/src/controllers/safeplace.js, api2/src/db.js, api2/src/models/User.js, api2/src/models/safePlace.js, client/package-lock.json
chicas hice los cambios para que los campos del form del front coincidan con el modelo de la base de datos, lo que me queda es ver como sacar la longitud y la latitud con la direccion que el usuario cargo
=> cambios post safe place

api2/package-lock.json, api2/package.json, api2/src/controllers/auth.js, api2/src/controllers/safeplace.js, api2/src/db.js, api2/src/middlewares/validateSchema.js, api2/src/models/User.js, api2/src/models/safePlace.js, api2/src/routes/safeplace.js, api2/src/schemas/safePlace.js, client/package-lock.json
chicas hice la validacion del post de safe place, lo hice con una libreria que se llama joi, asi que cuando hagan pull tienen que volver a hacer npm i . esta libreria nos va a servir para validar cualquier servicio que hagamos , asi evitamos que metan data incorrecta, en el caso de que no se cumplan con los campos requerido devuelve un 400
=> Validacion back end safe place

api2/.gitignore, api2/src/controllers/safeplace.js, api2/src/models/safePlace.js, api2/src/schemas/safePlace.js
le erre a una letra , en vez de email decia mail jaja
=> cambios shemas safe place

api2/src/models/safePlace.js
cambio modelo lugares seguros para utilizar luego la conversion de direcciona  coordenadas
=> cambiosmodelolugareseguros (#53)

api2/src/controllers/auth.js, api2/src/routes/safeplace.js, api2/src/schemas/safePlace.js, api2/src/services/auth0.js
el cambio que hice fue sacar el token de autorizacion de usuario, para que se pueda renderizar el mapa, asi como estaba solo iban a poder ver los lugares seguros solos los usuarios logueados
=> cambios get safe place

client/src/actions/actions.js
muchachas modifique la ruta de crear usuario, yo hice la prueba y anda todo ok los datos se guardan en la DB
=> cambio nombre de ruta

api2/src/controllers/auth.js, api2/src/models/safePlace.js, api2/src/routes/safeplace.js, api2/src/schemas/safePlace.js, client/src/Pages/IniciaSesion.jsx, client/src/Pages/RegistrateLugarSeguro.jsx, client/src/Reducers/Reducers.jsx, client/src/actions/actions.js
chicas ya esta hecha la integracion del login , asi que ahora una vez que se bajen los cambios nuevos, lo primero que tiene que hacer es registarse en la web, despues loguearse para poder hacer el post de lugares seguros, le agregue al modelo de la  base de datos la columna lastname que no la tenia, el id del usuario lo guarde en el store como userId y el token se gurda en el localStorage. Ya se esta enviando el token en el post de lugares seguros
=> integracion login

client/src/App.js, client/src/Components/Cards-Panel/Cards-Panel.css, client/src/Components/Cards-Panel/Cards-Panel.jsx, client/src/Components/Header/Header.jsx, client/src/Components/Popup/Popup.css, client/src/Components/Popup/Popup.jsx, client/src/Pages/Panel-Admin/Panel.css, client/src/Pages/Panel-Admin/Panel.jsx, client/src/Reducers/Reducers.jsx, client/src/actions/actions.js
Panel de control creado. Se puede filtrar por paises. Para mañana termino las funcionalidades de los botones
=> creacion panel de control

api2/configs/adminEmails.json, api2/src/controllers/safeplace.js, api2/src/routes/safeplace.js, api2/src/services/safeplace.js
http://localhost:3001/safe_place/admin/all_safe_place
=> all safe place admin

api2/src/app.js, api2/src/controllers/safeplace.js, api2/src/controllers/user.js, api2/src/models/User.js, api2/src/routes/user.js, api2/src/services/users.js
GET => http://localhost:3001/user/:id  (trae los datos de ese usuario)
PATCH => http://localhost:3001/user/:id 
body :
{
"name":"valetina",
"lastname":"bihu",
"phone":"566765",
"town":"buenos aires",
"country":"arge"
}
Esos datos son los que el usuario puede modificar , recuerden siempre loguearse para poder hacer cambios, sino no los va a autorizar . Para usar estos servicios manden siempre el token en los headers
=> get and update user data

client/src/App.js, client/src/Pages/User-Profile-Page/Content/AccountSettings.jsx, client/src/Pages/User-Profile-Page/Content/Content.jsx, client/src/Pages/User-Profile-Page/Content/Update.jsx, client/src/Pages/User-Profile-Page/LogoutBtn/LogoutBtn.jsx, client/src/Pages/User-Profile-Page/MainProfile.jsx, client/src/Pages/User-Profile-Page/SideBar/SideBar.jsx, client/src/Pages/User-Profile-Page/SideBar/UserProfile.jsx, client/src/Pages/User-Profile-Page/Styles/styles.css, client/src/Pages/User-Profile-Page/helpers/index.js
✔ Estilos del Componente Perfil de Usuario.
✔ Se agregó los respectivos cambios en App.js para que el componente pueda renderizarse en la ruta /profile.
=> Estilos Perfil de Usuario

client/src/Pages/IniciaSesion.jsx
✔Botón 'ingresá' ahora redirige a /profile -----> Componente Perfil de Usuario.
✔Validaciones hechas para que el campo email, se le introduzca una estructura de email y no cualquier cosa.
✔ Validaciones en el campo password. Lleva la misma estructura de password que del Componente Registrate.
=> Redireccionamiento de Inicio sesion a Perfil de usuario

client/src/Components/Cards-Panel/Cards-Panel.jsx, client/src/Components/Header/Header.jsx, client/src/Components/NavBar/NavBar.jsx, client/src/Components/Popup/Popup.jsx, client/src/Pages/Panel-Admin/Panel.css, client/src/Pages/Panel-Admin/Panel.jsx, client/src/Pages/User-Profile-Page/MainProfile.jsx, client/src/Pages/User-Profile-Page/SideBar/UserProfile.jsx, client/src/Reducers/Reducers.jsx, client/src/actions/actions.js
-Si estas logueado como admin, en el perfil de usuario se ve el boton "panel de admin"
-agregue al navbar el boton "mi cuenta" que te redirige a /profile con los datos del usuario logueado
=> Detalles panel 2

client/src/Reducers/Reducers.jsx, client/src/actions/actions.js
solo le agregue dos comas  que faltaban
=> faltaban dos comas

client/src/Pages/IniciaSesion.jsx
✔Corrección en validate password, porque no estaba permitiendo ingresar al perfil de usuario.
=> correccion en password

client/src/Components/Mapa/Map.jsx, client/src/Pages/RegistrateLugarSeguro.css, client/src/Pages/RegistrateLugarSeguro.jsx, client/src/Pages/Sities/Sitie.jsx, client/src/Pages/Sities/Sities.css
=> volver (#124)

api2/src/controllers/user.js, client/src/Components/Cards-Panel/Cards-Panel.jsx, client/src/Pages/User-Profile-Page/Content/AccountSettings.jsx, client/src/Reducers/Reducers.jsx, client/src/actions/actions.js
=> Cambios update user

client/src/Components/Mapa/Map.jsx
mostrar bien info de lugares en botones
=> infobotones

api2/src/services/safeplace.js, client/src/App.js, client/src/Components/Cards-Users/Cards-Users.css, client/src/Components/Cards-Users/Cards-Users.jsx, client/src/Pages/User-Profile-Page/SideBar/UserProfile.jsx, client/src/Pages/Usuarios/Usuarios.jsx, client/src/Reducers/Reducers.jsx, client/src/actions/actions.js
-Si sos Admin, aparece en "mi cuenta" el boton para administrar usuarios
- Te trae todos los usuarios y si es regular se puede pasar a admin
=> Panel usuarios

api2/src/controllers/safeplace.js, api2/src/routes/safeplace.js
un usuariio regular puede cambiar el estado de un lugar seguro a warning
=> change status safe place warnign

api2/src/models/User.js
La imagen que faltaba en la tabla del usuario.
Recuerden actualizar cada que hagan un cambio con modelos. 
En el archivo index de api2 poner el force en true, levantar el back, y luego volver a ponerlo en false y volver a levantar el back. 
Así se actualizan las tablas.
=> imgUserModel

client/src/Pages/IniciaSesion.jsx
☑️ Eliminando duplicado en link to='/registrate'.
=> Eliminando duplicado

client/src/Components/Mapa/Mapa.css, client/src/Components/Mapa/Mapa.jsx, client/src/Components/Mapa/Wave.jsx
✔️ Estilos tipo onda para la Landing Page.
=> Estilos Landing Page

client/src/Components/Cards-Users/Cards-Users.css, client/src/Components/Cards-Users/Cards-Users.jsx, client/src/Pages/Usuarios/Usuarios.css, client/src/Pages/Usuarios/Usuarios.jsx
-panel admin usuarios terminado
=> panel admin usuarios + swal

client/src/Components/Cards-Users/Cards-Users.css, client/src/Components/Cards-Users/Cards-Users.jsx, client/src/Components/Sidebar/Sidebar.css, client/src/Components/Sidebar/Sidebar.jsx, client/src/Pages/Usuarios/Usuarios.css, client/src/Pages/Usuarios/Usuarios.jsx
Si el usuario no esta logueado no puede comentar ni denunciar, los links dirigen a /iniciasesion
=> Sidebar botones

client/src/Pages/User-Profile-Page/Content/Content.jsx, client/src/Pages/User-Profile-Page/SideBar/SideBar.jsx
✔️ Corrección del margin-top entre NavBar y el formulario Perfil de usuario. 
Antes:
Ahora:
=> Correcion en el margen del form Perfil de usuario

api2/src/routes/user.js, client/src/App.js, client/src/Components/Cards-Users/Cards-Users.jsx, client/src/Components/Mapa/Map.jsx, client/src/Components/Sidebar/PopupsSideBarWarning.jsx, client/src/Pages/Usuarios/Usuarios.css
En el panel de usuarios, se puede pasar de admin a regular
=> de admin a regular

client/src/Components/Footer/Footer.css
=> Margen arreglado

client/src/Components/Sidebar/PopupsSideBar.css, client/src/Components/Sidebar/Sidebar.css
=> arreglo css mapa
